[build]
  publish = "public"
  command = "npm ci"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[functions."notify"]
  schedule = "*/15 * * * *"

[functions."ig-post"]
  schedule = "*/15 4-6,16-18 * * *"
